-- 교구/부서 콘텐츠(스펙 §5.8). BaseEntity 상속, 감사/소프트삭제/낙관락 컬럼은 V7~V9 관례를 따른다.
-- 본문 description은 마크다운 원본(TEXT), 본문 내 이미지는 media:{id}로 참조(스펙 §5). V9=events 점유 → V10.
-- parent_id는 자기참조 FK(계층). soft delete만 하므로 ON DELETE 절 불필요 — 자식 차단은 앱 레벨(살아있는 자식 검사).
CREATE TABLE departments (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    leader      VARCHAR(100),
    parent_id   BIGINT       REFERENCES departments (id),
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    created_by  BIGINT       REFERENCES members (id),
    updated_by  BIGINT       REFERENCES members (id),
    deleted_at  TIMESTAMP,
    version     BIGINT       NOT NULL DEFAULT 0
);

-- 기본 정렬 = sort_order, 미삭제만(스펙 §6 부분 인덱스).
CREATE INDEX idx_departments_sort_order ON departments (sort_order) WHERE deleted_at IS NULL;
