-- 갤러리(스펙 §5.12). 앨범은 BaseEntity(감사/소프트삭제/낙관락) 상속 — V7~V10 관례. V10=departments 점유 → V11.
-- 사진(gallery_photos)은 경량 연결행: created_at만(BaseTimeEntity), soft delete/version 없음. 해제=hard delete.
-- 앨범 description은 마크다운 원본(TEXT), 본문 이미지는 media:{id} 참조(차단삭제 LIKE 대상).
CREATE TABLE gallery_albums (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    created_by  BIGINT       REFERENCES members (id),
    updated_by  BIGINT       REFERENCES members (id),
    deleted_at  TIMESTAMP,
    version     BIGINT       NOT NULL DEFAULT 0
);

-- 앨범 목록 정렬 = created_at DESC, 미삭제만(스펙 §6 부분 인덱스).
CREATE INDEX idx_gallery_albums_created_at ON gallery_albums (created_at DESC) WHERE deleted_at IS NULL;

-- 사진: 앨범당 정렬은 (album_id, sort_order), media 차단삭제 FK 검색은 (media_id). deleted_at 없음 → 비부분 인덱스.
CREATE TABLE gallery_photos (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id   BIGINT       NOT NULL REFERENCES gallery_albums (id),
    media_id   BIGINT       NOT NULL REFERENCES media (id),
    caption    VARCHAR(500),
    sort_order INTEGER      NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

CREATE INDEX idx_gallery_photos_album_sort ON gallery_photos (album_id, sort_order);
CREATE INDEX idx_gallery_photos_media_id ON gallery_photos (media_id);
