-- 주보(스펙 §5.13). BaseEntity(감사·소프트삭제·낙관락) 상속 — V7~V11 관례. V11=gallery 점유 → V12.
-- media_id는 nullable + ON DELETE SET NULL: 활성 주보는 차단형 삭제로 보호되고, soft-deleted 주보만
--   media 하드삭제 시 자동 null화돼 FK 댕글링을 막는다(설계 §2.1). 활성 비-null은 앱 레이어가 보장.
CREATE TABLE bulletins (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    service_date DATE         NOT NULL,
    media_id     BIGINT       REFERENCES media (id) ON DELETE SET NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP,
    created_by   BIGINT       REFERENCES members (id),
    updated_by   BIGINT       REFERENCES members (id),
    deleted_at   TIMESTAMP,
    version      BIGINT       NOT NULL DEFAULT 0
);

-- 목록 정렬 = service_date DESC, 미삭제만(스펙 §6 부분 인덱스).
CREATE INDEX idx_bulletins_service_date ON bulletins (service_date DESC) WHERE deleted_at IS NULL;
-- media 차단삭제 FK 검색용(deleted_at 조건은 Provider 쿼리가 담당 → 비부분 인덱스).
CREATE INDEX idx_bulletins_media_id ON bulletins (media_id);
