-- 성경 통독 챌린지 D10 (docs/superpowers/specs/2026-07-06-bible-challenge-design.md).
-- 성경 구조(66권 1189장)는 코드 상수(BibleStructure) — 테이블 없음.
-- 종료일·하루 목표는 start_date/target_days에서 파생 — 저장하지 않는다.
CREATE TABLE bible_challenges (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    description TEXT,
    start_book  INT          NOT NULL,
    end_book    INT          NOT NULL,
    start_date  DATE         NOT NULL,
    target_days INT          NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    created_by  BIGINT       REFERENCES members (id),
    updated_by  BIGINT       REFERENCES members (id),
    deleted_at  TIMESTAMP,
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_bible_challenges_book_range
        CHECK (start_book BETWEEN 1 AND 66 AND end_book BETWEEN 1 AND 66 AND start_book <= end_book),
    CONSTRAINT ck_bible_challenges_target_days CHECK (target_days > 0)
);

-- 목록 기본 정렬 start_date DESC, 미삭제만(스펙 §6 부분 인덱스 관례).
CREATE INDEX idx_bible_challenges_start_date ON bible_challenges (start_date DESC) WHERE deleted_at IS NULL;

-- 참여 = 회원×챌린지, 현재 회독 포인터(chapters_read) + 완독 횟수(rounds_completed).
CREATE TABLE challenge_participations (
    id               BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id     BIGINT    NOT NULL REFERENCES bible_challenges (id),
    member_id        BIGINT    NOT NULL REFERENCES members (id),
    chapters_read    INT       NOT NULL DEFAULT 0,
    rounds_completed INT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP,
    created_by       BIGINT    REFERENCES members (id),
    updated_by       BIGINT    REFERENCES members (id),
    deleted_at       TIMESTAMP,
    version          BIGINT    NOT NULL DEFAULT 0,
    CONSTRAINT ck_challenge_participations_counts CHECK (chapters_read >= 0 AND rounds_completed >= 0)
);

-- 중복 참여 방지 + 취소 후 재참여 허용(부분 유니크 — members.phone 관례).
CREATE UNIQUE INDEX uq_challenge_participations_active
    ON challenge_participations (challenge_id, member_id) WHERE deleted_at IS NULL;
-- 마이페이지 참여 이력 조회.
CREATE INDEX idx_challenge_participations_member
    ON challenge_participations (member_id) WHERE deleted_at IS NULL;

-- 날짜별 읽음 로그 — 하루 1행 누적, 취소는 물리 삭제(포인터의 파생 기록이라 소프트삭제 부적합).
CREATE TABLE challenge_reading_logs (
    id               BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participation_id BIGINT    NOT NULL REFERENCES challenge_participations (id),
    read_date        DATE      NOT NULL,
    chapters         INT       NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    CONSTRAINT ck_challenge_reading_logs_chapters CHECK (chapters > 0),
    CONSTRAINT uq_challenge_reading_logs_day UNIQUE (participation_id, read_date)
);

-- 권한 시드 2건 (V2 패턴): 관리자에겐 관리+참여 모두, MEMBER(승인 교인)에겐 참여만.
INSERT INTO permissions (name, description) VALUES
    ('CHALLENGE_MANAGE',      '통독 챌린지 관리'),
    ('CHALLENGE_PARTICIPATE', '통독 챌린지 참여');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r
JOIN permissions p ON p.name IN ('CHALLENGE_MANAGE', 'CHALLENGE_PARTICIPATE')
WHERE r.name IN ('SUPER_ADMIN', 'ADMIN');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r
JOIN permissions p ON p.name = 'CHALLENGE_PARTICIPATE'
WHERE r.name = 'MEMBER';
