-- 문의하기(이슈 #50). 방문자(비로그인)가 남긴 문의를 관리자가 확인·완료체크·삭제한다.
-- 답변 본문 컬럼은 없다 — 답변은 담당자가 이메일/문자로 직접 발송하고(스펙 §2 No-SMTP), 시스템은 처리 여부만 추적한다.
-- created_by는 익명 제출이라 항상 NULL, updated_by는 완료 처리한 관리자가 들어간다(BaseEntity 감사).
CREATE TABLE inquiries (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(50)  NOT NULL,
    phone             VARCHAR(20)  NOT NULL,   -- digits-only 정규화 저장(members.phone 관례)
    email             VARCHAR(100),            -- 선택
    content           TEXT         NOT NULL,   -- 일반 텍스트(마크다운 아님 → media:{id} 참조 없음)
    privacy_agreed_at TIMESTAMP    NOT NULL,   -- 개인정보 수집·이용 동의 시각(동의 없으면 등록 자체가 거부됨)
    completed_at      TIMESTAMP,               -- NULL=미완료, 값=완료. 완료 취소 시 다시 NULL
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP,
    created_by        BIGINT       REFERENCES members (id),
    updated_by        BIGINT       REFERENCES members (id),
    deleted_at        TIMESTAMP,
    version           BIGINT       NOT NULL DEFAULT 0
);

-- 목록 기본 정렬 = created_at DESC, 미삭제만(스펙 §6 부분 인덱스).
CREATE INDEX idx_inquiries_created ON inquiries (created_at DESC) WHERE deleted_at IS NULL;
-- 관리자 기본 화면인 "미처리 문의" 전용 부분 인덱스.
CREATE INDEX idx_inquiries_pending ON inquiries (created_at DESC) WHERE deleted_at IS NULL AND completed_at IS NULL;

-- 문의 관리 권한(조회·완료체크·삭제 전부 이 권한 하나로 게이트).
INSERT INTO permissions (name, description) VALUES
    ('INQUIRY_MANAGE', '문의 관리');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r
JOIN permissions p ON p.name = 'INQUIRY_MANAGE'
WHERE r.name IN ('SUPER_ADMIN', 'ADMIN');
