-- 차량운행 신청(이슈 #62, docs/superpowers/specs/2026-07-21-vehicle-run-request-design.md).
-- 관리자가 운행일을 등록하고 승인 교인(MEMBER)이 날짜별로 탑승을 신청한다 — 배차·정원·탑승확인 없음(YAGNI).
CREATE TABLE vehicle_runs (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departs_at TIMESTAMP NOT NULL,   -- 운행 일시. 신청 마감 시각을 겸한다(지나면 신청 불가)
    note       TEXT,                 -- 예: "토요일 오후, 학원 앞 경유"
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by BIGINT    REFERENCES members (id),
    updated_by BIGINT    REFERENCES members (id),
    deleted_at TIMESTAMP,
    version    BIGINT    NOT NULL DEFAULT 0
);

-- 회원 목록 = 다가오는 운행일 오름차순, 미삭제만(스펙 §6 부분 인덱스 관례).
CREATE INDEX idx_vehicle_runs_departs_at ON vehicle_runs (departs_at) WHERE deleted_at IS NULL;

-- 탑승 신청 = 회원×운행일. 연락처·이름은 저장하지 않는다 — 명단 조회 시 members에서 읽는다.
CREATE TABLE vehicle_requests (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT       NOT NULL REFERENCES vehicle_runs (id),
    member_id       BIGINT       NOT NULL REFERENCES members (id),
    pickup_location VARCHAR(200) NOT NULL,  -- 픽업 장소 자유 텍스트
    note            TEXT,                   -- 동승 인원·특이사항
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP,
    created_by      BIGINT       REFERENCES members (id),
    updated_by      BIGINT       REFERENCES members (id),
    deleted_at      TIMESTAMP,
    version         BIGINT       NOT NULL DEFAULT 0
);

-- 중복 신청 방지 + 취소 후 재신청 허용(부분 유니크 — challenge_participations 관례).
CREATE UNIQUE INDEX uq_vehicle_requests_active
    ON vehicle_requests (run_id, member_id) WHERE deleted_at IS NULL;
-- 운행일별 명단 조회.
CREATE INDEX idx_vehicle_requests_run ON vehicle_requests (run_id) WHERE deleted_at IS NULL;

-- 권한 시드 2건 (V13 패턴): 관리자에겐 관리+신청 모두, MEMBER(승인 교인)에겐 신청만.
INSERT INTO permissions (name, description) VALUES
    ('VEHICLE_MANAGE', '차량운행 관리'),
    ('VEHICLE_APPLY',  '차량운행 신청');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r
JOIN permissions p ON p.name IN ('VEHICLE_MANAGE', 'VEHICLE_APPLY')
WHERE r.name IN ('SUPER_ADMIN', 'ADMIN');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r
JOIN permissions p ON p.name = 'VEHICLE_APPLY'
WHERE r.name = 'MEMBER';
