CREATE TABLE positions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    sort_order INTEGER     NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_positions_name UNIQUE (name)
);

-- 직분 목록 정렬용(스펙 §6). positions엔 deleted_at이 없어 부분 인덱스가 아니다.
CREATE INDEX idx_positions_sort_order ON positions (sort_order);

-- NOTE(#8 members): members.position_id BIGINT FK -> positions(id) ON DELETE SET NULL은
--   members 테이블 생성 마이그레이션에서 추가한다(직분이 members보다 먼저 구현되므로 여기선 보류).
