-- 권한(고정 카탈로그). 타임스탬프 없음(스펙 §3.2).
CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_permissions_name UNIQUE (name)
);

-- 역할(관리자가 동적 생성). created_at만, soft-delete/version 없음 → 물리 삭제.
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    priority    INTEGER     NOT NULL,
    is_system   BOOLEAN     NOT NULL DEFAULT FALSE,
    description VARCHAR(255),
    created_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uq_roles_name UNIQUE (name)
);
CREATE INDEX idx_roles_priority ON roles (priority);

-- 역할 ↔ 권한 (다대다). 역할 물리 삭제 시 링크 동반 삭제(role 측 CASCADE). permission 측은 RESTRICT — 고정 카탈로그 보호.
-- NOTE(#8 members): member_roles(member_id, role_id)와 members FK, 최초 SUPER_ADMIN 계정 시드는
--   members 마이그레이션에서 추가한다. member_roles.role_id -> roles(id)는 RESTRICT(앱 레벨 블로킹 삭제).
CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES roles (id)       ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE RESTRICT
);

-- 권한 12종(스펙 §3.3)
INSERT INTO permissions (name, description) VALUES
    ('SERMON_WRITE',    '설교 등록/수정/삭제'),
    ('NOTICE_WRITE',    '공지 등록/수정/삭제'),
    ('EVENT_WRITE',     '일정 등록/수정/삭제'),
    ('DEPT_WRITE',      '교구/부서 등록/수정/삭제'),
    ('MEMBER_MANAGE',   '회원 조회/관리'),
    ('ROLE_MANAGE',     '역할·권한 관리'),
    ('POSITION_MANAGE', '직분 관리'),
    ('MEDIA_MANAGE',    '미디어 업로드/조회/삭제'),
    ('TAG_MANAGE',      '태그 추가/수정/삭제'),
    ('GALLERY_WRITE',   '갤러리 업로드/수정/삭제'),
    ('GALLERY_VIEW',    '갤러리 조회(회원 전용 열람)'),
    ('BULLETIN_WRITE',  '주보 업로드/수정/삭제');

-- 역할 4종(스펙 §3.3)
INSERT INTO roles (name, priority, is_system, description, created_at) VALUES
    ('SUPER_ADMIN', 1000, TRUE,  '최고 관리자',  now()),
    ('ADMIN',        900, TRUE,  '관리자',       now()),
    ('MEMBER',       100, FALSE, '교인',         now()),
    ('USER',           0, TRUE,  '일반 사용자',  now());

-- SUPER_ADMIN·ADMIN = 전 12권한
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name IN ('SUPER_ADMIN', 'ADMIN');

-- MEMBER = GALLERY_VIEW
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.name = 'GALLERY_VIEW'
WHERE r.name = 'MEMBER';
-- USER = 권한 없음(시드 INSERT 없음 — 의도적)
