-- 회원. 정체성(id·uuid) 불변, phone/name/email/password 가변. soft delete. 낙관락·작성자 없음(스펙 §5.2/§6).
CREATE TABLE members (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL,
    phone          VARCHAR(20)  NOT NULL,   -- 숫자만 정규화 저장(예: 01012345678)
    name           VARCHAR(50)  NOT NULL,
    password       VARCHAR(255) NOT NULL,   -- BCrypt 해시
    email          VARCHAR(255),
    position_id    BIGINT,
    terms_agreed   BOOLEAN   NOT NULL DEFAULT FALSE,
    privacy_agreed BOOLEAN   NOT NULL DEFAULT FALSE,
    agreed_at      TIMESTAMP,
    created_at     TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP,
    deleted_at     TIMESTAMP,
    CONSTRAINT fk_members_position FOREIGN KEY (position_id)
        REFERENCES positions (id) ON DELETE SET NULL   -- V1에서 이연된 FK(직분 물리 삭제 대응)
);
CREATE UNIQUE INDEX uq_members_uuid         ON members (uuid);
CREATE UNIQUE INDEX uq_members_phone_active ON members (phone) WHERE deleted_at IS NULL;  -- 번호 재활용

-- 회원 ↔ 역할 (다대다). role 측 RESTRICT = 앱 레벨 블로킹 삭제(V2 NOTE 계약). member 측 CASCADE.
CREATE TABLE member_roles (
    member_id BIGINT NOT NULL,
    role_id   BIGINT NOT NULL,
    PRIMARY KEY (member_id, role_id),
    CONSTRAINT fk_mr_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_mr_role   FOREIGN KEY (role_id)   REFERENCES roles (id)   ON DELETE RESTRICT
);
CREATE INDEX idx_member_roles_member ON member_roles (member_id);
CREATE INDEX idx_member_roles_role   ON member_roles (role_id);
