-- 글로벌 태그 풀 + 다형 연결(content_tags). 모든 콘텐츠 도메인이 단일 태그 풀을 공유한다(스펙 §5.11).
CREATE TABLE tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL
);

-- 콘텐츠 ↔ 태그 다형 연결. resource_id는 어느 도메인이든 가리키므로 DB FK를 못 건다(앱 레벨 무결성).
-- tag_id만 FK + ON DELETE CASCADE: 태그 물리 삭제 시 연결 자동 정리.
-- (앱도 TagService.delete에서 deleteByTag로 명시 정리하고, CASCADE는 백스톱.)
CREATE TABLE content_tags (
    tag_id        BIGINT      NOT NULL,
    resource_type VARCHAR(30) NOT NULL,   -- SERMON / NOTICE / EVENT / GALLERY_ALBUM
    resource_id   BIGINT      NOT NULL,
    PRIMARY KEY (tag_id, resource_type, resource_id),
    CONSTRAINT fk_content_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

-- PK 앞 prefix (tag_id, resource_type)가 태그 필터 조회를 커버하므로,
-- 콘텐츠→태그 역조회용 인덱스만 추가한다(스펙 §6).
CREATE INDEX idx_content_tags_resource ON content_tags (resource_type, resource_id);
