-- 중앙 미디어 라이브러리(스펙 §5.10). 이미지·PDF를 한 테이블에 모으고 mime_type으로 용도를 구분한다.
-- 본문은 media:{id}로 참조하며, 갤러리·주보는 FK로 재사용한다. soft delete/version 없음 — 차단형 하드 삭제 도메인.
CREATE TABLE media (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename    VARCHAR(255) NOT NULL,             -- 원본 파일명(표시용)
    stored_path VARCHAR(512) NOT NULL,             -- volume 내 실제 저장 경로(FileStorage 키)
    mime_type   VARCHAR(100) NOT NULL,             -- image/jpeg, application/pdf 등(매직바이트 스니핑 결과)
    size        BIGINT       NOT NULL,             -- 바이트
    uploaded_by BIGINT       NOT NULL REFERENCES members (id),  -- 업로더(members는 soft delete뿐이라 타깃 불멸)
    created_at  TIMESTAMP    NOT NULL
);

-- 라이브러리 그리드: 타입 필터 + 최신순(스펙 §6).
CREATE INDEX idx_media_mime_created ON media (mime_type, created_at DESC);
