-- 설교 콘텐츠(스펙 §5.5). BaseEntity를 상속하는 첫 엔티티 — 감사/소프트삭제/낙관락 컬럼을 여기서 처음 확정.
-- 본문 content는 마크다운 원본(TEXT), 본문 내 이미지는 media:{id}로 참조(스펙 §5). V6은 media 제약이 점유 → V7.
CREATE TABLE sermons (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    preacher    VARCHAR(100) NOT NULL,
    series      VARCHAR(100),
    scripture   VARCHAR(200),
    content     TEXT,
    video_url   VARCHAR(500),
    audio_url   VARCHAR(500),
    preached_at DATE         NOT NULL,
    view_count  BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    created_by  BIGINT       REFERENCES members (id),
    updated_by  BIGINT       REFERENCES members (id),
    deleted_at  TIMESTAMP,
    version     BIGINT       NOT NULL DEFAULT 0
);

-- 목록 기본 정렬 = preached_at DESC, 미삭제만(스펙 §6 부분 인덱스).
CREATE INDEX idx_sermons_preached_at ON sermons (preached_at DESC) WHERE deleted_at IS NULL;
