-- 공지 콘텐츠(스펙 §5.7). BaseEntity 상속, 감사/소프트삭제/낙관락 컬럼은 V7(sermons) 관례를 따른다.
-- 본문 content는 마크다운 원본(TEXT), 본문 내 이미지는 media:{id}로 참조(스펙 §5). V7은 sermons가 점유 → V8.
CREATE TABLE notices (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    content     TEXT,
    is_pinned   BOOLEAN      NOT NULL DEFAULT FALSE,
    view_count  BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    created_by  BIGINT       REFERENCES members (id),
    updated_by  BIGINT       REFERENCES members (id),
    deleted_at  TIMESTAMP,
    version     BIGINT       NOT NULL DEFAULT 0
);

-- 목록 기본 정렬 = is_pinned DESC, created_at DESC, 미삭제만(스펙 §6 부분 인덱스).
CREATE INDEX idx_notices_pinned_created ON notices (is_pinned DESC, created_at DESC) WHERE deleted_at IS NULL;
