-- 일정/행사 콘텐츠(스펙 §5.6). BaseEntity 상속, 감사/소프트삭제/낙관락 컬럼은 V7(sermons)/V8(notices) 관례를 따른다.
-- 본문 description은 마크다운 원본(TEXT), 본문 내 이미지는 media:{id}로 참조(스펙 §5). V8=notices 점유 → V9.
CREATE TABLE events (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    location    VARCHAR(200),
    start_at    TIMESTAMP    NOT NULL,
    end_at      TIMESTAMP,
    all_day     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    created_by  BIGINT       REFERENCES members (id),
    updated_by  BIGINT       REFERENCES members (id),
    deleted_at  TIMESTAMP,
    version     BIGINT       NOT NULL DEFAULT 0
);

-- 기본 정렬·범위 조회 = start_at, 미삭제만(스펙 §6 부분 인덱스).
CREATE INDEX idx_events_start_at ON events (start_at) WHERE deleted_at IS NULL;
